# Generated by Django 3.1.4 on 2021-04-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('artist_name', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='shop/images')),
            ],
        ),
    ]
