# Generated by Django 3.1.4 on 2021-04-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='dimension',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(upload_to='shop/artworks'),
        ),
    ]
