# Generated by Django 3.1.4 on 2021-05-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210501_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('dimensions', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='')),
                ('date', models.DateField()),
            ],
        ),
    ]
